export const GET_GROUPS_FOR_USER = 'GET_GROUPS_FOR_USER';
export const SEARCH_GROUPS = 'SEARCH_GROUPS';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
