export const GET_GROUPS_FOR_USER = 'GET_GROUPS_FOR_USER';
export const SEARCH_GROUPS = 'SEARCH_GROUPS';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const CREATE_GROUP = 'CREATE_GROUP';
export const ADD_MEMBER = 'ADD_MEMBER';

export const GET_TASKS = 'GET_TASKS';
export const CREATE_TASKS = 'CREATE_TASKS';
export const UPDATE_TASK = 'UPDATE_TASK';
